language: python
matrix:
    include:
        - python: 3.6
          dist: trusty
          sudo: false
        - python: 3.7
          dist: xenial
          sudo: true
install:
  - pip3 install -r requirements.txt
before_script:
  - python3 dep_app/rest/api.py
script:
  - python3 -m unittest dep_app/tests/test_rest.py


