language: python
matrix:
    include:
        - python: 3.7
          dist: xenial
          sudo: true
install:
  - pip3 install -r requirements.txt
script:
  - python3.7 -m unittest dep_app/tests/test_rest.py


